config/routes.rb
TicTacToeRails::Application.routes.draw do
  resources :ckims


  resources :games do
    get 'opponent_move', :on => :member
    get 'get_position', :on => :member
  end
  resources :users

  root :to => 'ttt#index'

  match '/sign_in'  => 'users#sign_in',  :as => 'sign_in'
  match '/sign_out' => 'users#sign_out', :as => 'sign_out'
  match '/sign_up'  => 'users#new',  :as => 'sign_up'
  match '/ttt/move', :controller => "ttt", :action => "move"
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :first_user, :class_name => 'User'
  belongs_to :second_user, :class_name => 'User'
  attr_accessible :accepted, :completed, :email, :position, :turn
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games
  attr_accessible :email, :password_hash, :password, :name, :login_token

  def password
    ""
  end
  def password= passwd
    password_hash = Digest::MD5.hexdigest(passwd)
  end

  def self.find_or_create_by_email email
    user = find_by_email(email)
    if user.nil?
      user = create!(:email => email, :login_token => Digest::MD5.hexdigest(Time.now.to_i.to_s))
    end
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include ApplicationHelper

  # GET /games
  # GET /games.json
  def index
    @games = Game.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    if current_user.nil?
      session[:original_path] = request.original_fullpath
      query_params = {}
      query_params.merge!(:login_token => params[:login_token]) if !params[:login_token].nil?
      redirect_to params[:login_token] ? edit_user_path(query_params) : sign_in_path(query_params)
      return
    elsif params[:login_token]
      @game = Game.find(params[:id])
      redirect_to @game
      return
    end

    @game = Game.find(params[:id])
    @first_player = @game.first_user || User.new
    @second_player = @game.second_user || User.new
    @current_player = current_user || User.new
    @current_player_symbol = current_user.id == @game.first_user.id ? "x" : "o"
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    # make sure user is signed in
    if !user_signed_in?
      flash[:error] = "You need to log in first"
      redirect_to new_game_path
      return
    end
    # make sure email address is filled in
    if params[:email].empty?
      flash[:error] = "You need to specify an email address"
      redirect_to new_game_path
      return
    end
    opponent = User.find_or_create_by_email(params[:email])
    game = Game.new
    game.turn = "x"
    if params[:i_play_first]
      game.first_user_id = current_user.id
      game.second_user_id = opponent.id
    else
      game.first_user_id = opponent.id
      game.second_user_id = current_user.id
    end
    if game.save
      redirect_to game, notice: 'Game invitation has been sent.'
      query_params = {}
      query_params.merge!(:login_token => opponent.login_token) if opponent.login_token
      Email.request_game(opponent.email, current_user.email, game_url(game, query_params)).deliver
    else
      render action: "new"
    end
  end

  def opponent_move
    board = params[:board]
    turn = params[:turn]
    @game = Game.find(params[:id])
    @game.board = board.join
    @game.turn = turn
    @game.save!
    render :json => true
  end

  def get_position
    @game = Game.find(params[:id])
    render :json => {
      :board => (@game.board || "---------").chars.to_a,
      :turn => @game.turn,
    }
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/ttt_controller.rb
class TttController < ApplicationController
  def index
  end

  def move
    clj = JRClj.new("ttt.core")
    board = clj.vec(params[:board].map { |cell| clj.symbol(cell) })
    turn = clj.symbol(params[:turn])
    position = clj.init_position(board, turn)
    speed = params[:speed]
    if (speed == "slow_option") then
      sleep(2)
    end
    render :json => clj.random_best_move(position)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  # GET /users/new
  # GET /users/new.json
  def new
    @user = params[:login_token] ? User.find_by_login_token(params[:login_token]) : User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def edit
    @user = params[:login_token] ? User.find_by_login_token(params[:login_token]) : User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.login_token = nil
    @user.password_hash = hash_password(@user.password)
    if (@user.update_attributes(params[:user]))
      session[:user_id] = @user.id
      redirect_to(session[:original_path] || root_path)
    else
      render action: "edit"
    end
  end

  # POST /users
  # POST /users.json
  def create
    params[:user][:password_hash] = hash_password(params[:user][:password])
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def sign_out
    session[:user_id] = nil
    redirect_to root_path
  end

  def sign_in
    if params[:email]
      @user = User.find_by_email(params[:email])
      if @user
        if @user.password_hash == hash_password(params[:password])
          session[:user_id] = @user.id
          redirect_to root_path
        else
          flash[:error] = "Password does not match"
          redirect_to sign_in_path
        end
      else
        flash[:error] = "No user by that email"
        redirect_to sign_in_path
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_signed_in?
    session[:user_id]
  end
  def current_user
    @user ||= User.find(session[:user_id])
  rescue
    session[:user_id] = nil
    nil
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/ttt_helper.rb
module TttHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def hash_password password
    Digest::MD5.hexdigest(password)
  end
end

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div id="content">
<h2>Listing games</h2>

<table class="listing">
  <tr>
    <th></th>
    <th>Id</th>
    <th>Players</th>
    <th>Board</th>
    <th>Turn</th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <% first_user = game.first_user || User.new %>
  <% second_user = game.second_user || User.new %>
  <tr>
    <td><%= link_to 'Show', game %></td>
    <td><%= game.id %></td>
    <td><%= first_user.email %><br />
        <%= second_user.email %></td>
    <td>
      <pre><%= game.board.nil? ? "" : game.board.chars.each_slice(3).map { |row| " " + row.join(" | ") }.join("\n-----------\n") %></pre>
    </td>

    <td align="center"><%= game.turn %></td>
    <td>
      <% if current_user && (first_user.email == current_user.email || second_user.email == current_user.email) %>
        <%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>
</div>

app/views/games/new.html.erb
<div id="content">
<h2>New game</h2>
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= label_tag :i_play_first %>
    <%= check_box_tag :i_play_first %>
  </div>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Cancel', root_path %>
</div>

app/views/games/show.html.erb
<div id="ttt">
  <p id="notice"><%= notice %></p>
  <%= render :partial => 'shared/board_display' %>
  <%= link_to 'Back', games_path %>
</div>

<div id="legend_track">
  <div id="legend">
    <ul>
      <li id="first_player"><img src='/assets/oars.png' height="20" width="20"> <%= @first_player.name %></li>
      <li id="second_player"><img src='/assets/lifepreserver.png' height="20" width="20"> <%= @second_player.name %></li>
    </ul>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
  game_id = <%= @game.id %>;
  $(function() {
      set_players(
        {name: '<%= @first_player.name %>', email: '<%= @first_player.email %>'},
        {name: '<%= @second_player.name %>', email: '<%= @second_player.email %>'},
        {name: '<%= @current_player.name %>', email: '<%= @current_player.email %>'},
        '<%= @current_player_symbol %>');
      check_for_move();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TicTacToeRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" %>
  <%= javascript_include_tag "http://code.jquery.com/jquery-1.9.1.js" %>
  <%= javascript_include_tag "http://code.jquery.com/ui/1.10.3/jquery-ui.js" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jQueryRotate.2.2" %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans|Pacifico' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Della+Respira' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="banner">
    <% if user_signed_in? %>
      <a href="<%= games_url %>">Games</a>
    <% end %>
    <div class="right">
    <% if user_signed_in? %>
      <%= current_user.name %> <%= link_to('Logout', sign_out_path, :method => :delete) %>
    <% else %>
      <%= link_to('Login', sign_in_path)  %> or <%= link_to('Sign Up', sign_up_path) %>
    <% end %>
    </div>
  </div>
  <h1><a href="/">Tic Tac Toe</a></h1>
  <h2 id="message">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if flash[:error] %>
      <p class="error"><%= flash[:error] %></p>
    <% end %>
  </h2>
  <%= yield %>
  <img src="/assets/boat.png" id="boat">
  <img src="/assets/water.png" id="water">
</body>
</html>

app/views/shared/_board_display.html.erb
<div class="squares">
  <% 9.times do |i|
    classes = []
    classes << "square"
    classes << "left"     if i%3 == 0 
    classes << "h-middle" if i%3 == 1 
    classes << "right"    if i%3 == 2 
    classes << "top"      if i/3 == 0
    classes << "v-middle" if i/3 == 1
    classes << "bottom"   if i/3 == 2 %>

    <div id="t-<%= i %>" class="<%= classes.join(" ") %>" onclick="javascript:send_move(<%= i %>, current_player_symbol)"></div>
  <% end %>
</div>
<div id="play_again_dialog" title="Play Again?" class="hidden">Human wins. Do you want to play again?</div>

app/views/ttt/index.html.erb
  <div id="ttt"></div>


  <div id="set_first_player" class="hidden">
    <h2>Play against:</h2>
    <form action="javascript:return false" method="get" accept-charset="utf-8">
      <input type="button" name="human_first" id="human_first" value="You vs Computer"
      onclick="javascript:set_players({name:'Human'}, {name:'Computer'}, {name: 'Human'}, 'x')"/><br />
      <input type="button" name="computer_first" id="computer_first" value="Computer vs You"
      onclick="javascript:set_players({name: 'Computer'}, {name: 'Human'}, {name: 'Human'}, 'o')"/><br />
      <input type="button" name="against_another_player" id="Opponent First" value="You vs Opponent" onclick="window.location='<%= url_for :controller => :games, :action => :new %>'"/>
    </form>
  </div>

  <div id="board_display">
  <%= render :partial => 'shared/board_display' %>
  </div>
  <script type="text/javascript" charset="utf-8">
    $('#board_display').addClass('hidden')
  </script>
<div id="loading">
  <img src="assets/lifepreserver.png">
</div>
<form name="speed_form">
<div id="options">
  <div class="item"><input type="radio" name="speed" id="fast_option" checked="checked"/><label for="fast_option">Computer plays fast</label></div>
  <div class="item"><input type="radio" name="speed" id="slow_option" /><label for="slow_option">Computer plays slow</label></div>
</div>
</form>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div id="content">
<h2>Editing user</h2>
<%= render 'form' %>
<%= link_to 'Back', root_path %>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="content">
<h2>New user</h2>
<%= render 'form' %>
<%= link_to 'Back', root_path %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/sign_in.html.erb
<div id="content">
  <form action="/sign_in" method="post">

    <div class="field">
      <label for="email">Email</label>
      <input type="text" name="email">
    </div>

    <div class="field">
      <label for=":password">Password</label>
      <input type="password" name="password" />
    </div>
    <input type="submit" value="Sign In">
  </form>
</div>